# Generated by Django 4.0.4 on 2022-04-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_musicmodel_alter_usermodel_age_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.musicmodel', verbose_name='Ism')),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumModels',
        ),
    ]
