# Generated by Django 4.0.4 on 2022-04-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_albummodel_delete_albummodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicmodel',
            name='groups',
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crudapp.musicmodel', verbose_name='guruh_nomi'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ism'),
        ),
    ]
