# Generated by Django 4.0.4 on 2022-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_remove_musicmodel_groups_alter_albummodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('user_name', models.CharField(max_length=50, verbose_name='Foydalanuvchi_nomi')),
                ('email', models.EmailField(max_length=254)),
                ('images', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.RemoveField(
            model_name='albummodel',
            name='name',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='AlbumModel',
        ),
        migrations.DeleteModel(
            name='MusicModel',
        ),
    ]
